services:
  suitecrm-app:
    build: .
    restart: always
    ports:
      - "8080:80" # <-- ESTA ES LA LÍNEA MÁGICA
    volumes:
      - crm_data:/var/www/html
    depends_on:
      - suitecrm-db

  suitecrm-db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=TuPasswordRootFuerte
      - MARIADB_DATABASE=suitecrm_db
      - MARIADB_USER=suitecrm_user
      - MARIADB_PASSWORD=TuPasswordCrmFuerte
    volumes:
      - db_data:/var/lib/mysql

volumes:
  crm_data:
  db_data:
